"""Add Fossil model

Revision ID: bca7533affbe
Revises: a556217e6bd2
Create Date: 2026-07-01 17:32:24.868967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca7533affbe'
down_revision = 'a556217e6bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fossils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fossil_type', sa.String(length=100), nullable=False),
    sa.Column('geological_period', sa.String(length=100), nullable=False),
    sa.Column('location_found', sa.String(length=150), nullable=False),
    sa.Column('date_found', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fossils')
    # ### end Alembic commands ###
